/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simplerts.editor;

import simplerts.map.Terrain;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.image.BufferStrategy;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.tree.DefaultMutableTreeNode;
import simplerts.map.Cell;
import simplerts.Game;
import simplerts.map.BackEndMap;
import simplerts.map.MapIO;
import simplerts.gfx.Assets;
import simplerts.map.FrontEndMap;
import simplerts.utils.TaskManager;
import simplerts.utils.TimerTask;

/**
 *
 * @author Markus
 */
public class MapEditor extends javax.swing.JFrame {
    
    public static final int MINE_START_DISTANCE = 5;

    private static boolean placeable(EditorObject object, MapEditor e) {
        for(int x = object.gridX; x < object.gridX + object.gridWidth; x++)
        {
            for(int y = object.gridY; y < object.gridY + object.gridHeight; y++)
            {
                if(!(x >= 0 && x < e.map.getCells().length && y >= 0 && y < e.map.getCells()[0].length))
                {
                    return false;
                } else {
                    Rectangle r1 = new Rectangle(object.gridX, object.gridY, object.gridWidth, object.gridHeight);
                    for(EditorObject editorObject : e.editorObjects)
                    {
                        if((object.name.equals("Goldmine") && editorObject.name.equals("StartingLocation")) || (object.name.equals("StartingLocation") && editorObject.name.equals("Goldmine")))
                        {
                            if(r1.intersects(new Rectangle(editorObject.gridX - MINE_START_DISTANCE, editorObject.gridY - MINE_START_DISTANCE, editorObject.gridWidth + MINE_START_DISTANCE * 2, editorObject.gridHeight + MINE_START_DISTANCE * 2)))
                            return false;
                        }
                        if(r1.intersects(new Rectangle(editorObject.gridX, editorObject.gridY, editorObject.gridWidth, editorObject.gridHeight)))
                            return false;
                    }
                    if(!e.map.getCells()[x][y].isAvailable())
                        return false;
                }
            }
        }
        
        return true;
    }

    BackEndMap map;
    FrontEndMap renderMap;
    EditorPanel editorPanel;
    TaskManager tm;
    ArrayList<EditorObject> editorObjects;
    
    /**
     * Creates new form MapEditor
     */
    public MapEditor() {
        Assets.setup();
        initComponents();
        initCustomComponents();
    }
    
    public static boolean showGrid = true;
    public static JFileChooser fc = new JFileChooser();
    public static Terrain currentTerrain;

    private void initCustomComponents()
    {
        map = new BackEndMap(100, 100);
        renderMap = new FrontEndMap(map);
        editorPanel = new EditorPanel(renderMap);
        editorPanel.setPreferredSize(new Dimension(map.getSize()));
        currentTerrain = Assets.darkGrass;
        editorObjects = new ArrayList<>();
        editorPanel.setEditorObjects(editorObjects);
        tm = new TaskManager();
        initTree();
    }
    
    private void initTree()
    {
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("JTree");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Terrain");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode(Assets.grass);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode(Assets.darkGrass);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode(Assets.dirt);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode(Assets.trees);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Objects");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Gold mine");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Start location");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        scrollPane1 = new java.awt.ScrollPane();
        minimapCanvas = new java.awt.Canvas();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem3.setText("New...");
        jMenu1.add(jMenuItem3);

        jMenuItem1.setLabel("Save");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setLabel("Open");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("View");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Grid");
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(minimapCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(minimapCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int result = fc.showSaveDialog(this);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            MapIO.saveMap(fc.getSelectedFile(), map, editorObjects);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int result = fc.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            map = MapIO.loadMap(fc.getSelectedFile());
            renderMap = new FrontEndMap(map);
            editorPanel.setMap(renderMap);
            editorPanel.setSize(map.getSize());
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            MapEditor e = new MapEditor();
            EditorPanel canvas1 = e.editorPanel;
            e.scrollPane1.add(canvas1);
            canvas1.setScrollPane(e.scrollPane1);
            e.minimapCanvas.createBufferStrategy(1);
            EditorMouseListener ml = new EditorMouseListener();
            EditorMouseMotionListener mml = new EditorMouseMotionListener();
            canvas1.addMouseListener(ml);
            canvas1.addMouseMotionListener(mml);
            e.setVisible(true);

            Thread thread = new Thread(new Runnable() {
                public void run() {
                    canvas1.setSize(e.map.getSize());
                    while (true) {
                        if(ml.isMouseDown)
                        {
                            editorClick(mml, e, 1);
                        }
                        if(ml.isRightMouseDown)
                        {
                            editorClick(mml, e, 3);
                        }
                        canvas1.repaint();
                    }
                }
            });
            thread.start();
            
            Thread updateMinimap = new Thread(() -> {
                e.tm.addTask(updateMinimap(e));
                while(true)
                {
                    e.tm.update();
                }     
            });
            updateMinimap.start();
        });
    }
    
    public static TimerTask updateMinimap(MapEditor m)
    {
            TimerTask t = new TimerTask(100, () -> {
                BufferStrategy bs = m.minimapCanvas.getBufferStrategy();
                Graphics g = bs.getDrawGraphics();
                g.drawImage(m.renderMap.getMinimapImage(184, 184, true), 0, 0, null);
                bs.show();
                g.dispose();
                m.tm.addTask(updateMinimap(m));
            });
            
            return t;
    }
    
    public static void maskMap(BackEndMap map, int startX, int startY)
    {
        Cell[][] cells = map.getCells();
        Terrain terrain;
        for(int y = startY-1; y < startY+3; y++)
        {
            for(int x = startX-1; x < startX+3; x++)
            {
                int getTile = 0;
                if(y >= 0 && x >= 0 && y < cells[0].length && x < cells.length && cells[x][y].getTerrain() != Assets.grass)
                {
                    terrain = cells[x][y].getTerrain();
                    if((y-1) >= 0 && cells[x][y-1].getTerrain() == cells[x][y].getTerrain())
                        getTile += 1;
                    if((x+1) < cells.length && cells[x+1][y].getTerrain() == cells[x][y].getTerrain())
                        getTile += 2;
                    if((y+1) < cells[0].length && cells[x][y+1].getTerrain() == cells[x][y].getTerrain())
                        getTile += 4;
                    if((x-1) >= 0 && cells[x-1][y].getTerrain() == cells[x][y].getTerrain())
                        getTile += 8;
                    
                    cells[x][y].setTile(terrain.terrainSquare[getTile]);
                    
                    if(getTile == 15)
                    {
                        boolean NE = false, SE = false, SW = false, NW = false;
                        if((y-1) >= 0 && (x+1) < cells.length && cells[x+1][y-1].getTerrain() == cells[x][y].getTerrain())
                            NE = true;
                        if((x+1) < cells.length && (y+1) < cells[0].length && cells[x+1][y+1].getTerrain() == cells[x][y].getTerrain())
                            SE = true;
                        if((y+1) < cells[0].length && (x-1) >= 0 && cells[x-1][y+1].getTerrain() == cells[x][y].getTerrain())
                            SW = true;
                        if((x-1) >= 0 && (y-1) >= 0 && cells[x-1][y-1].getTerrain() == cells[x][y].getTerrain())
                            NW = true;
                        
                        if(NE && SE && SW && NW)
                            continue;
                        if(NE && SE && SW)
                            cells[x][y].setTile(terrain.getSquare()[18]);
                        if(SE && SW && NW)                         
                            cells[x][y].setTile(terrain.getSquare()[19]);
                        if(SW && NW && NE)
                            cells[x][y].setTile(terrain.getSquare()[20]);
                        if(NW && NE && SE)
                            cells[x][y].setTile(terrain.getSquare()[21]);
                        if(NW && SE && !NE && !SW)
                            cells[x][y].setTile(terrain.getSquare()[16]);
                        if(NE && SW && !NW && !SE)
                            cells[x][y].setTile(terrain.getSquare()[17]);
                            
                    }
                    System.out.println(terrain.terrainSquare[getTile] + " " + getTile);
                }
            }
        }
    }
    
    public static void maskMap(BackEndMap map)
    {
        for(int gx = 0; gx < map.getCells().length; gx+=3)
        {
            for(int gy = 0; gy < map.getCells()[0].length; gy+=3)
            {
                maskMap(map, gx, gy);
            }
        }
    }
    
    public static void editorClick(EditorMouseMotionListener mml, MapEditor e, int button)
    {
        if(button == 1)
        {
            if((e.jTree1.getSelectionPath()) != null)
            {
                DefaultMutableTreeNode selected = (DefaultMutableTreeNode)e.jTree1.getSelectionPath().getLastPathComponent();
                if(selected.isLeaf() && selected.getParent().toString().equals("Terrain"))
                {
                    for(int i = mml.posX / Game.CELLSIZE; i < mml.posX/Game.CELLSIZE + 2; i++)
                        {
                            for(int j = mml.posY / Game.CELLSIZE; j < mml.posY/Game.CELLSIZE + 2; j++)
                            {
                                if(i >= 0 && i < e.map.getCells().length && j >= 0 && j < e.map.getCells()[0].length)
                                {
                                    Cell cell = e.map.getCells()[i][j];
                                    cell.setTerrain(((Terrain)selected.getUserObject()));
                                }
                            }
                        }
                        maskMap(e.map, mml.posX/Game.CELLSIZE, mml.posY/Game.CELLSIZE);            
                } else if (selected.isLeaf() && selected.getParent().toString().equals("Objects"))
                {
                    if(selected.toString().equals("Gold mine"))
                    {
                        EditorObject goldmine = new EditorObject(mml.posX/Game.CELLSIZE, mml.posY/Game.CELLSIZE, 3, 3, Assets.loadAndResizeImage("/mine.png", 150, 150), "Goldmine");
                        if(placeable(goldmine, e))
                            e.editorObjects.add(goldmine);
                    } else if (selected.toString().equals("Start location"))
                    {
                        EditorObject startLoc = new EditorObject(mml.posX/Game.CELLSIZE, mml.posY/Game.CELLSIZE, 4, 4, Assets.loadAndResizeImage("/startinglocation.png", 200, 200), "StartingLocation");
                        if(placeable(startLoc, e))
                        {
                            e.editorObjects.add(startLoc);
                        }
                    }
                }
            }
        } else if (button == 3)
        {
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private java.awt.Canvas minimapCanvas;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
